/** Auto-generated by pnpm i18n:sync-ui-locales — do not edit by hand */
import enMessages from './locales/en.json';
import { LOCALE_UI_FALLBACK } from './locale-fallback';

export const UI_MESSAGE_LOCALE_FILES = ["en", "aa", "ab", "af", "ak", "am", "ar", "as", "av", "ay", "az", "ba", "be", "bg", "bh", "bm", "bn", "bo", "br", "bs", "ca", "ch", "co", "cs", "cv", "cy", "da", "de", "dv", "dz", "ee", "el", "eo", "es", "et", "eu", "fa", "ff", "fi", "fj", "fo", "fr", "fy", "ga", "gd", "gl", "gn", "gu", "gv", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "ig", "is", "it", "iu", "ja", "jv", "ka", "kk", "kl", "km", "kn", "ko", "kr", "ku", "kv", "ky", "la", "lb", "lg", "li", "ln", "lo", "lt", "lv", "mg", "mh", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "nb", "ne", "nl", "no", "nr", "ny", "oc", "om", "or", "os", "pa", "pl", "ps", "pt", "qu", "rn", "ro", "ru", "rw", "sa", "sd", "se", "sg", "sh", "si", "sk", "sl", "sm", "sn", "so", "sq", "sr", "ss", "st", "su", "sv", "sw", "ta", "te", "tg", "th", "ti", "tk", "tl", "tn", "to", "tr", "ts", "tt", "tw", "ty", "ug", "uk", "ur", "uz", "ve", "vi", "wo", "xh", "yi", "yo", "zh", "zu"] as const;

export type UiMessageLocaleFile = (typeof UI_MESSAGE_LOCALE_FILES)[number];

const fileSet = new Set<string>(UI_MESSAGE_LOCALE_FILES);

type MessageTree = Record<string, unknown>;

/** Fill gaps in auto-generated locale files (formHints, localeGroups, …) from en. */
function deepMergeMessages(base: MessageTree, override: MessageTree): MessageTree {
  const result: MessageTree = { ...base };
  for (const [key, value] of Object.entries(override)) {
    if (
      value !== null &&
      typeof value === 'object' &&
      !Array.isArray(value) &&
      typeof result[key] === 'object' &&
      result[key] !== null &&
      !Array.isArray(result[key])
    ) {
      result[key] = deepMergeMessages(result[key] as MessageTree, value as MessageTree);
    } else {
      result[key] = value;
    }
  }
  return result;
}

/**
 * Resolve locale to an on-disk messages file (direct file or mapped fallback).
 */
export function resolveUiMessageLocale(locale: string, visited = new Set<string>()): string {
  if (visited.has(locale)) return 'en';
  visited.add(locale);
  if (fileSet.has(locale)) return locale;
  const mapped = LOCALE_UI_FALLBACK[locale];
  if (mapped) return resolveUiMessageLocale(mapped, visited);
  return 'en';
}

export async function loadUiMessages(locale: string) {
  const target = resolveUiMessageLocale(locale);
  if (target === 'en') return enMessages;
  try {
    const mod = await import(`./locales/${target}.json`);
    const loaded = (mod.default ?? mod) as MessageTree;
    return deepMergeMessages(enMessages as MessageTree, loaded) as typeof enMessages;
  } catch {
    return enMessages;
  }
}
