/** Auto-generated by pnpm i18n:sync-ui-locales — do not edit by hand */
import enMessages from './locales/en.json';
import arMessages from './locales/ar.json';
import deMessages from './locales/de.json';
import esMessages from './locales/es.json';
import frMessages from './locales/fr.json';
import ruMessages from './locales/ru.json';

export const UI_MESSAGE_LOCALES = ["en","ar","de","es","fr","ru"] as const;

export type UiMessageLocale = (typeof UI_MESSAGE_LOCALES)[number];

export const UI_MESSAGES: Record<UiMessageLocale, typeof enMessages> = {
  en: enMessages,
  ar: arMessages,
  de: deMessages,
  es: esMessages,
  fr: frMessages,
  ru: ruMessages,
};

export function loadUiMessages(locale: string) {
  if (locale in UI_MESSAGES) return UI_MESSAGES[locale as UiMessageLocale];
  return UI_MESSAGES.en;
}
