import { Injectable } from '@nestjs/common';
import type { PdfExportTemplateCode } from '@prisma/client';
import type { TreeViewDataResponse } from '@family/shared';

export type ExportPersonRow = {
  id: string;
  displayName: string;
  birthYear?: number | null;
  deathYear?: number | null;
};

export type ExportBuildInput = {
  templateCode: PdfExportTemplateCode;
  workspaceName: string;
  title: string;
  persons: ExportPersonRow[];
  treeData?: TreeViewDataResponse | null;
  familyBranchName?: string;
  branding?: {
    displayName?: string | null;
    primaryColor?: string | null;
    secondaryColor?: string | null;
  };
};

@Injectable()
export class ExportTemplateService {
  listTemplates() {
    return [
      {
        code: 'FAMILY_BOOK_STANDARD',
        label: 'Family Book (Standard)',
        description: 'Multi-page narrative book with person list and timeline summary.',
        format: 'A4',
      },
      {
        code: 'FAMILY_BOOK_A2',
        label: 'Family Book (A2 branch)',
        description: 'Large-format branch book — ideal for printing a family line.',
        format: 'A2',
      },
      {
        code: 'TREE_POSTER_A3',
        label: 'Tree Poster (A3)',
        description: 'Landscape pedigree poster for printing.',
        format: 'A3',
      },
    ];
  }

  buildHtml(input: ExportBuildInput): string {
    if (input.templateCode === 'TREE_POSTER_A3') {
      return this.buildTreePosterHtml(input);
    }
    if (input.templateCode === 'FAMILY_BOOK_A2') {
      return this.buildFamilyBookA2Html(input);
    }
    return this.buildFamilyBookHtml(input);
  }

  private buildFamilyBookA2Html(input: ExportBuildInput): string {
    const color = input.branding?.primaryColor ?? '#2d5a27';
    const branch = input.familyBranchName ? ` · ${escapeHtml(input.familyBranchName)}` : '';
    const persons = input.persons
      .map(
        (p) =>
          `<tr><td>${escapeHtml(p.displayName)}</td><td>${p.birthYear ?? ''}${p.deathYear ? `–${p.deathYear}` : ''}</td></tr>`,
      )
      .join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>${escapeHtml(input.title)}</title>
  <style>
    @page { size: A2 portrait; margin: 18mm; }
    body { font-family: Georgia, serif; margin: 0; padding: 32px; color: #1a1a1a; }
    h1 { font-size: 3rem; color: ${color}; margin-bottom: 0.25rem; }
    .cover { border-bottom: 4px solid ${color}; padding-bottom: 28px; margin-bottom: 36px; }
    table { width: 100%; border-collapse: collapse; font-size: 1.1rem; }
    td { padding: 8px 12px; border-bottom: 1px solid #ddd; }
    td:first-child { font-weight: 600; width: 55%; }
  </style>
</head>
<body>
  <div class="cover">
    <h1>${escapeHtml(input.title)}</h1>
    <p>${escapeHtml(input.workspaceName)}${branch} · ${input.persons.length} persons</p>
  </div>
  <h2>Branch members</h2>
  <table>${persons}</table>
  <p style="margin-top:24px;color:#666">FAMILY_BOOK_A2 — Family Memory Platform</p>
</body>
</html>`;
  }

  private buildFamilyBookHtml(input: ExportBuildInput): string {
    const color = input.branding?.primaryColor ?? '#2d5a27';
    const persons = input.persons
      .map(
        (p) =>
          `<li>${escapeHtml(p.displayName)}${p.birthYear ? ` (${p.birthYear}${p.deathYear ? `–${p.deathYear}` : ''})` : ''}</li>`,
      )
      .join('');

    const nodeCount = input.treeData?.nodes.length ?? input.persons.length;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>${escapeHtml(input.title)}</title>
  <style>
    body { font-family: Georgia, serif; margin: 40px; color: #1a1a1a; }
    h1 { font-size: 2.2rem; color: ${color}; margin-bottom: 0.25rem; }
    .cover { border-bottom: 3px solid ${color}; padding-bottom: 24px; margin-bottom: 32px; }
    .meta { color: #555; margin-top: 8px; }
    ul { columns: 2; line-height: 1.6; }
    @media print { body { margin: 20mm; } }
  </style>
</head>
<body>
  <div class="cover">
    <h1>${escapeHtml(input.title)}</h1>
    <p class="meta">${escapeHtml(input.workspaceName)} · ${nodeCount} persons</p>
  </div>
  <h2>Family Members</h2>
  <ul>${persons}</ul>
  <p class="meta">Generated by Family Memory Platform — FAMILY_BOOK_STANDARD</p>
</body>
</html>`;
  }

  private buildTreePosterHtml(input: ExportBuildInput): string {
    const color = input.branding?.primaryColor ?? '#2d5a27';
    const nodes = (input.treeData?.nodes ?? []).slice(0, 48);
    const cards = nodes
      .map((n) => {
        const birth = n.birthDate ? new Date(n.birthDate).getFullYear() : '';
        const death = n.deathDate ? new Date(n.deathDate).getFullYear() : '';
        const years = birth ? `${birth}${death ? `–${death}` : ''}` : '';
        return `<div class="node"><strong>${escapeHtml(n.label)}</strong><br/><span>${years}</span></div>`;
      })
      .join('');

    const fallback = input.persons
      .slice(0, 48)
      .map(
        (p) =>
          `<div class="node"><strong>${escapeHtml(p.displayName)}</strong><br/><span>${p.birthYear ?? ''}${p.deathYear ? `–${p.deathYear}` : ''}</span></div>`,
      )
      .join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>${escapeHtml(input.title)} — Tree Poster</title>
  <style>
    @page { size: A3 landscape; margin: 15mm; }
    body { font-family: 'Segoe UI', sans-serif; margin: 0; padding: 24px; background: #f8f6f0; }
    h1 { text-align: center; color: ${color}; margin-bottom: 24px; }
    .grid { display: grid; grid-template-columns: repeat(6, 1fr); gap: 12px; }
    .node { background: #fff; border: 2px solid ${color}; border-radius: 8px; padding: 10px; text-align: center; font-size: 12px; min-height: 64px; }
    .node span { color: #666; }
  </style>
</head>
<body>
  <h1>${escapeHtml(input.title)}</h1>
  <div class="grid">${cards || fallback}</div>
</body>
</html>`;
  }
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
